# Generated by Django 3.1.2 on 2022-03-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8)),
                ('cor', models.CharField(max_length=15)),
                ('fabricante', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=15)),
                ('dataentrada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
