# Generated by Django 3.1.2 on 2022-03-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='parado',
            field=models.BooleanField(default=False),
        ),
    ]
