# Generated by Django 3.1.2 on 2022-03-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_carro_parado'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='dateupdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='carro',
            name='dataentrada',
            field=models.DateTimeField(),
        ),
    ]
