# Generated by Django 3.1.2 on 2022-03-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_auto_20220329_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='dataentrada',
            new_name='data_entrada',
        ),
        migrations.RenameField(
            model_name='carro',
            old_name='dateupdate',
            new_name='date_update',
        ),
    ]
