# Generated by Django 3.1.2 on 2022-03-29 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0004_auto_20220329_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='data_entrada',
            new_name='dataentrada',
        ),
    ]
