# Generated by Django 3.1.2 on 2022-03-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0005_auto_20220329_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='dataentrada',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
