# Generated by Django 3.1.2 on 2022-03-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0007_manobrista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='placa',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
