# Generated by Django 3.1.2 on 2022-03-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0008_auto_20220329_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='manobrista',
            name='saida',
            field=models.BooleanField(default=True),
        ),
    ]
